---
title: "World Happiness Report"
author: "Koki Ando"
date: "3/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Preparation

## Packages
```{r}
library(data.table)
library(tidyverse)
library(corrplot)
library(plotly)
```


```{r}
setwd("/Users/KokiAndo/Desktop/R/R report/World Happiness")
#(https://www.kaggle.com/unsdsn/world-happiness)
wh15 <- fread("2015.csv", data.table = FALSE)
wh16 <- fread("2016.csv", data.table = FALSE)
wh17 <- fread("2017.csv", data.table = FALSE)
wh15$year <- 2015
wh16$year <- 2016
wh17$year <- 2017

names(wh17)[2] <- "Happiness Rank"
names(wh17)[3] <- "Happiness Score"
names(wh17)[6] <- "Economy (GDP per Capita)"
names(wh17)[8] <- "Health (Life Expectancy)"
names(wh17)[11] <- "Trust (Government Corruption)"
names(wh17)[12] <- "Dystopia Residual"

wh15_17 <- bind_rows(wh15,wh16,wh17)
names(wh15_17)[5] <- "SD_error"
wh15_17 <- wh15_17 %>% select(Country:year,-Region, -SD_error)
```

```{r}
names(wh15_17) <- c("Country","Happiness_Rank","Happiness_Score","Economy_GDP",
                 "Family","Health","Freedom","Trust",
                 "Generosity","Dystopia_Residual","year")
```




# Correlation
```{r}
corrplot(cor(wh15_17 %>% select(Happiness_Score:Dystopia_Residual)), method = "circle",type = "upper")
```

# Ranking Transition (coloured by year)
```{r}
wh15_17$Country <- as.factor(wh15_17$Country)
wh15_17$year <- as.factor(wh15_17$year)
ggplot(wh15_17, aes(x=Happiness_Rank, y = Country, colour = year)) + geom_point()
```

```{r}
ggplot(wh15_17 %>% filter(year==2017), aes(x= Happiness_Score,y= 
                                             reorder(Country,Happiness_Score))) + 
  geom_point(colour = "red", alpha = .5) + 
  geom_segment(aes(yend=reorder(Country, Happiness_Score)), xend = 0, colour="pink", alpha = .5) 
```

# Scatter Plot
```{r}
ggplot(wh15_17 %>% filter(year == 2017), aes(x=Health, y=Happiness_Score, colour=Economy_GDP)) + 
  geom_point() + 
  geom_smooth()
```

```{r}
plot_ly(data = wh15_17, 
        x=~Health, y=~Happiness_Score, color=~Economy_GDP, type = "scatter",
        text = ~paste("Country:", Country))
```


```{r}
world <- map_data('world')
ggplot() + geom_polygon(data = world, 
                             aes(x = long, y=lat, group = group),
                             colour = "black",
                             fill ="orange")
```

[Reference](https://stackoverflow.com/questions/30706124/ploting-the-world-map-in-r)
```{r}
world <- map_data('world')
world <- world %>% filter(region != "Antarctica")
world <- fortify(world)
happiness.score17 <- wh15_17 %>% select(Country, Happiness_Score, year) %>% filter(year == 2017)
head(happiness.score17)
ggplot() + 
  geom_map(data=world, map=world,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="black") + 
  geom_map(data=happiness.score17, map=world,
                  aes(fill=Happiness_Score, map_id=Country),
                  colour="black") + 
  scale_fill_continuous(low="red", high="yellow", 
                               guide="colorbar")
```

[参考](http://gg-hogehoge.hatenablog.com/entry/2013/09/23/212746)
[参考2](http://www.statsoft.org/wp-content/uploads/2016/09/Lecture6_HKMapVis.html)
[参考3](https://www.kaggle.com/swl554/visualizing-happiness-around-the-globe)


#Economy vs Happiness scatter plot

```{r}
plot_ly(data = wh15_17 %>% filter(year == 2017), 
        x=~Economy_GDP, y=~Happiness_Score, type = "scatter",
        text = ~paste("Country:", Country))
```

# Happiness score by region(boxplot)
```{r}
names(wh16)[4] <- "Happiness_Score"
ggplot(wh16, aes(x=Region, y= Happiness_Score, colour = Region)) + geom_boxplot() + geom_point()
```



